# For local development only - DO NOT commit real API keys!
# For Streamlit Cloud: Set this in the Streamlit Cloud dashboard under "Secrets"
# Get your key from: https://console.groq.com/
GROQ_API_KEY = "your-groq-api-key-here"
